"""adjust_sauce_table

Revision ID: 2bd44f46143d
Revises: 45a0bfc0e66b
Create Date: 2025-01-28 01:43:21.332749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bd44f46143d'
down_revision = '45a0bfc0e66b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sauce', sa.Column('stock', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sauce', 'stock')
    # ### end Alembic commands ###
