"""sauce_parameter_in_pizzatype

Revision ID: 65237ac39fbf
Revises: 2bd44f46143d
Create Date: 2025-01-29 07:39:50.856259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65237ac39fbf'
down_revision = '2bd44f46143d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pizza_type', sa.Column('sauce_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'pizza_type', 'sauce', ['sauce_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pizza_type', type_='foreignkey')
    op.drop_column('pizza_type', 'sauce_id')
    # ### end Alembic commands ###
